#pragma once

#define MIRYOKU_ALPHAS_QWERTY
#define MIRYOKU_EXTRA_COLEMAKDH
#define MIRYOKU_TAP_DEFAULT
#define MIRYOKU_NAV_VI
#define MIRYOKU_CLIPBOARD_MAC
#define MIRYOKU_LAYERS_DEFAULT
#define MIRYOKU_MAPPING_DEFAULT

#include "miryoku.h"

#undef  U_TAPPING_TERM
#define U_TAPPING_TERM 160
